author: RamsesA
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.github.rakama.plugins.cat.CATeleport
name: CA-Teleport
startup: startup
version: '1.0'
commands:
   catp:
      description: Enable or disable altitude teleportation
      usage: /<command> [enable, disable, status] [playername]
      permission: <plugin name>.catp
      permission-message: You don't have permission.
   casync:
      description: Enable or disable block synchronization across altitude layers
      usage: /<command> [enable, disable, status] [playername]
      permission: <plugin name>.casync
      permission-message: You don't have permission.