author: RamsesA
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.github.rakama.plugins.cat.CATeleport
name: CA-Teleport
startup: startup
version: '0.1.2'
commands:
   cat:
      description: Enable or disable altitude options
      usage: /<command> [tp, sync] [enable, disable, status]
      permission: <plugin name>.cat
      permission-message: You don't have permission.